#!/bin/bash
RABBIT_SHINY=${PWD}
#PIPELINE_ROUTE=../Pipeline_Output
PIPELINE_ROUTE=$@
echo "PIPELINE_ROUTE=$PIPELINE_ROUTE"
#export PATH=${PIPELINE_ROUTE}R/bin/:$PATH
#export R_LIBS=${PIPELINE_ROUTE}R_libs_3.2.3
Rscript ${RABBIT_SHINY}/getWeightedVotingModels.R ${RABBIT_SHINY}
mkdir -p ${RABBIT_SHINY}/outputs ${RABBIT_SHINY}/errors ${RABBIT_SHINY}/AUC_Result ${RABBIT_SHINY}/Pipeline_Result ${RABBIT_SHINY}/weightedVoting
cd ${PIPELINE_ROUTE}
for localedir in $(ls -d cv_loop_*)
# check for existence of predictions.txt file generated by first model
do
  if [ -f ${localedir}/model_1/predictions.txt ]; then
    echo $localedir" in directory "$PWD
    #qsub -o ${RABBIT_SHINY}/outputs/${localedir}.txt -e ${RABBIT_SHINY}/errors/${localedir}.txt ${RABBIT_SHINY}/run.rabbit.shiny.sh ${RABBIT_SHINY} ${PIPELINE_ROUTE}/${localedir} ${localedir}_out.csv ${localedir}_auc_out.csv
    ${RABBIT_SHINY}/run.rabbit.shiny.sh ${RABBIT_SHINY} ${PIPELINE_ROUTE}/${localedir} ${localedir}_out.csv ${localedir}_auc_out.csv
  fi
done
